_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.12
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.12
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
PF_rate:
    value: 0.8
batch_size:
    value: 100
bench:
    value: false
bound_ratio:
    value: 5
connection_wise:
    value: false
data:
    value: cifar100
death:
    value: global_magnitude
death_rate:
    value: 0.05
decay_frequency:
    value: 25000
decay_schedule:
    value: cosine
density:
    value: 0.1
dst:
    value: false
epochs:
    value: 160
filter_dst:
    value: true
fix:
    value: false
fix_num_operation:
    value: 0
fp16:
    value: false
gpm_filter_pune:
    value: true
grad_flow:
    value: false
grow_mask_not:
    value: false
growth:
    value: global_gradients
indicate_method:
    value: test
iters:
    value: 1
kernal_wise:
    value: false
l1:
    value: 0
l2:
    value: 0.0005
large_death_rate:
    value: 0.8
layer_interval:
    value: 1000
log_interval:
    value: 100
lr:
    value: 0.1
mag_wise:
    value: true
mask_wise:
    value: false
max_threads:
    value: 10
mest:
    value: true
mest_dst:
    value: true
mgpu:
    value: false
minumum_ratio:
    value: 0.5
model:
    value: ResNet50
momentum:
    value: 0.9
new_zero:
    value: true
no_cuda:
    value: false
no_grow_mask:
    value: false
nolrsche:
    value: false
optimizer:
    value: sgd
random_init:
    value: false
redistribution:
    value: none
resume:
    value: null
save:
    value: 17455104494997215.pt
save_features:
    value: false
seed:
    value: 41
sparse:
    value: true
sparse_init:
    value: fixed_ERK
start_epoch:
    value: 1
start_layer_rate:
    value: 0.5
stop_dst_epochs:
    value: 30
stop_gmp_epochs:
    value: 130
test_batch_size:
    value: 128
update_frequency:
    value: 1000
valid_split:
    value: 0.1
wandb_mode:
    value: online
wandb_project:
    value: he_dst
workers:
    value: 4
world_size:
    value: -1
